import type { Metadata } from 'next';
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from '@/theme';
import { SnackBarProvider } from '@/hooks/SnackBarContext';
import './globals.css';
import { Providers } from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Quiz App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
